In [12]:
import torch
import numpy as np
torch.__version__

'1.6.0+cu101'

In [13]:
np_array = np.array([1,2,3,4,5,6])
print(np_array)
np_array.dtype

In [9]:
x = torch.from_numpy(np_array)

In [11]:
type(x) 

torch.Tensor

In [19]:
np_array_2d = np.arange(0,12)

In [20]:
print(np_array_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
np_array_2d =np_array_2d.reshape(4,3)

In [24]:
np_array_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
x2 = torch.from_numpy(np_array_2d)

In [26]:
x2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [31]:
x2[0,0] = 100

In [32]:
x2

tensor([[100, 100, 100],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11]])

In [29]:
np_array_2d

array([[100, 100, 100],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [33]:
np_array_cp = np.arange(1,20)
tensor_x1 = torch.tensor(np_array_cp)
tensor_x2 = torch.from_numpy(np_array_cp)

In [34]:
tensor_x1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [35]:
tensor_x2

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [36]:
np_array_cp[0] = 100

In [37]:
tensor_x1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [38]:
tensor_x2

tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19])

In [39]:
tensor_x2[1] = 1000

In [40]:
tensor_x2

tensor([ 100, 1000,    3,    4,    5,    6,    7,    8,    9,   10,   11,   12,
          13,   14,   15,   16,   17,   18,   19])

In [41]:
np_array_cp

array([ 100, 1000,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19])

In [42]:
tensor_x1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [43]:
torch.Tensor([1,2,3,4])

tensor([1., 2., 3., 4.])

In [44]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [45]:
torch.tensor([1.,2,3,4])

tensor([1., 2., 3., 4.])

In [48]:
# close to zero
torch.empty(4,2)

tensor([[2.0257e+01, 4.5846e-41],
        [2.0257e+01, 4.5846e-41],
        [4.4842e-44, 0.0000e+00],
        [1.5695e-43, 0.0000e+00]])

In [51]:
torch.zeros(4,4, dtype=torch.int64)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [53]:
torch.ones(4,3,dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [55]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [57]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

# change type of tensor

In [58]:
x = torch.tensor([1,2,3])

In [60]:
x.dtype

torch.int64

In [69]:
x = x.type(torch.int32)

In [70]:
x.dtype

torch.int32

# random numbers

In [72]:
# uniform distribution
torch.rand(4,3)

tensor([[0.6018, 0.2378, 0.1750],
        [0.8443, 0.8501, 0.8634],
        [0.4630, 0.3831, 0.2735],
        [0.6453, 0.8911, 0.6332]])

In [74]:
# normal distribution
torch.randn(4,3)

tensor([[-0.3140, -0.0582, -0.2649],
        [-0.1105, -3.9007, -0.4088],
        [-0.0792,  0.4577,  1.0767],
        [ 0.1317,  0.4462,  1.1664]])

In [78]:
torch.randint(low= 0,high=10, size=(5,5))

tensor([[6, 2, 0, 9, 1],
        [4, 8, 4, 6, 5],
        [7, 5, 6, 7, 1],
        [8, 8, 3, 5, 2],
        [0, 1, 8, 1, 1]])

In [85]:
x = torch.zeros(3,4)

In [87]:
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [86]:
torch.rand_like(x)

tensor([[0.5873, 0.6726, 0.4764, 0.5844],
        [0.2960, 0.0749, 0.6646, 0.2751],
        [0.3329, 0.8354, 0.7966, 0.6328]])

In [95]:
torch.manual_seed(10)

In [96]:
torch.rand_like(x)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [97]:
torch.rand_like(x)

tensor([[0.7041, 0.5573, 0.6959, 0.9849],
        [0.2924, 0.4823, 0.6150, 0.4967],
        [0.4521, 0.0575, 0.0687, 0.0501]])

In [98]:
torch.rand_like(x)

tensor([[0.0108, 0.0343, 0.1212, 0.0490],
        [0.0310, 0.7192, 0.8067, 0.8379],
        [0.7694, 0.6694, 0.7203, 0.2235]])

In [99]:
x = torch.arange(10)

In [103]:
x.shape

torch.Size([10])

In [104]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [105]:
z = x.view(2,5)

In [106]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [107]:
x[0] = 1000

In [108]:
x

tensor([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [109]:
z

tensor([[1000,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

## Tensor Arithmetic

In [110]:
x = torch.tensor([1,2,3,4.])

In [111]:
y = torch.tensor([5,6,7,8.])

In [112]:
x+y

tensor([ 6.,  8., 10., 12.])

In [113]:
torch.add(x,y)

tensor([ 6.,  8., 10., 12.])

In [114]:
x*y

tensor([ 5., 12., 21., 32.])

In [115]:
x.mul(y)

tensor([ 5., 12., 21., 32.])

In [116]:
x

tensor([1., 2., 3., 4.])

In [117]:
x.mul_(y)

tensor([ 5., 12., 21., 32.])

In [118]:
x

tensor([ 5., 12., 21., 32.])

In [119]:
a = torch.tensor([1,2,3,4])

In [120]:
b = torch.tensor([5,6,7,8])

In [121]:
a*b

tensor([ 5, 12, 21, 32])

In [122]:
a.dot(b)

tensor(70)

In [126]:
np_a = np.arange(0,10)

In [127]:
a = torch.from_numpy(np_a)

In [128]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
a = a.reshape(2,5)

In [131]:
b = torch.from_numpy(np_a)

In [132]:
b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
b = b.reshape(5,2)

In [134]:
b

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [135]:
torch.mm(a,b)

tensor([[ 60,  70],
        [160, 195]])

In [136]:
torch.mm(b,a)

tensor([[  5,   6,   7,   8,   9],
        [ 15,  20,  25,  30,  35],
        [ 25,  34,  43,  52,  61],
        [ 35,  48,  61,  74,  87],
        [ 45,  62,  79,  96, 113]])

In [137]:
a @ b

tensor([[ 60,  70],
        [160, 195]])

In [138]:
b @ a

tensor([[  5,   6,   7,   8,   9],
        [ 15,  20,  25,  30,  35],
        [ 25,  34,  43,  52,  61],
        [ 35,  48,  61,  74,  87],
        [ 45,  62,  79,  96, 113]])

In [139]:
a 

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [143]:
a.type(torch.float64)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]], dtype=torch.float64)