### 1. Perform standard imports
Import torch and NumPy

In [16]:
# CODE HERE


### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [17]:
# CODE HERE


### 3. Create a NumPy array called "np_arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [18]:
# CODE HERE


array([3, 4, 2, 4, 4, 1])

### 4. Create a tensor "x" from the array above

In [21]:
# CODE HERE


torch.int64

### 5. Change the dtype of x from 'int64' to 'float64'

In [26]:
# CODE HERE


torch.float64

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [27]:
# CODE HERE


tensor([[3., 4.],
        [2., 4.],
        [4., 1.]], dtype=torch.float64)

### 7. Return the right-hand column of tensor x

In [ ]:
# CODE HERE


### 8. Without changing x, return a tensor of square values of x and square root of x
There are several ways to do this.

In [32]:
# CODE HERE


tensor([ 9., 16.,  4., 16., 16.,  1.], dtype=torch.float64)

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x

In [49]:
# CODE HERE


tensor([[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]])

In [50]:
# CODE HERE


tensor([[1, 0, 1],
        [0, 0, 1],
        [0, 1, 1]])

### 10. Find the matrix product of x and y

In [51]:
# CODE HERE


tensor([[0, 2, 0],
        [0, 1, 0],
        [1, 2, 1]])