# Linear Algebra Review
Python is a great programming language and with the help of a few popular libraries such numpy and matplotlib it becomes a powerful environment for Linear Algebra computing.

Numpy Documentation - This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

##### 1) Matrices and Vectors 
Rectangulare array of numbers
<img src="image/matrix.png">

## Numpy Array 

In [11]:
import numpy as np

##### 1) Matrices and Vectors 
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

In [12]:
# Create a rank 1 array
a = np.array(
    [
        [1,2,3,4],
        [1,4,5,6],
        [1,2,3,4]
    ]
)  
print (a)
print (type(a))            
print (a.shape)

[[1 2 3 4]
 [1 4 5 6]
 [1 2 3 4]]
<class 'numpy.ndarray'>
(3, 4)


##### 1.1) Change an element of the array 

In [13]:
a = np.array(
    [
        [1,2,3,4],
        [1,4,5,6],
        [1,2,3,4]
    ])
print (a)
a[0,0] = 100
print ()
print (a)

[[1 2 3 4]
 [1 4 5 6]
 [1 2 3 4]]

[[100   2   3   4]
 [  1   4   5   6]
 [  1   2   3   4]]


##### 1.2) Numpy functions

<font color="red"> **Datatypes**

In [14]:
a = np.array(
    [
        [1,2,3,4],
        [1,4,5,6],
        [1,2,3,4]
    ]
)
print (a)
print (type(a[0,0]))
print ()
a = np.array(
    [
        [1.2,2,3,4],
        [1,4,5,6],
        [1,2,3,4]
    ]
)  
print (a)
print (type(a[0,0]))

[[1 2 3 4]
 [1 4 5 6]
 [1 2 3 4]]
<class 'numpy.int64'>

[[1.2 2.  3.  4. ]
 [1.  4.  5.  6. ]
 [1.  2.  3.  4. ]]
<class 'numpy.float64'>


<font color="red"> **Compute sum of all elements in matrix**

In [15]:
x = np.array([
        [1,2,1],[3,4,1]])

print (x)
print (np.sum(x))  
print (np.sum(x, axis=0))  
print (np.sum(x, axis=1))  

[[1 2 1]
 [3 4 1]]
12
[4 6 2]
[4 8]


<font color="red"> **Create an array of all zeros**

In [16]:
a = np.zeros((4,4))  
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<font color="red"> **Create an array of all ones ** 

In [17]:
a = np.ones((2,5))   
a             

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<font color="red"> **Create a constant array**

In [18]:
a = np.full((4,4), 7)  
a               

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

<font color="red"> **Create an identity matrix**

In [19]:
a = np.eye(4)       
a            

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<font color="red"> **Create an array filled with random values**

In [20]:
a = np.random.random((5,5)) 
a                    

array([[0.76256362, 0.01293506, 0.84376607, 0.73948311, 0.08605531],
       [0.92549117, 0.56768581, 0.8225958 , 0.66554279, 0.18860485],
       [0.49527677, 0.70415029, 0.12764767, 0.74069811, 0.57698094],
       [0.90306337, 0.95927229, 0.03434256, 0.34999518, 0.9959636 ],
       [0.37072637, 0.51423836, 0.22911421, 0.88665052, 0.23237169]])

<font color="red"> **slicing to pull out the subarray**

In [21]:
a = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ])
print (a)
print ()
b = a[:1, :3]
print (b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[1 2 3]]


##### 2) Matrix Addition
<img src="image/matrix-sum.png">

In [22]:
x = np.ones((4,7))
print (x)
y = np.full((4,7), 4.3)
print (y)
z = x+y
print ()
print (z)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[4.3 4.3 4.3 4.3 4.3 4.3 4.3]
 [4.3 4.3 4.3 4.3 4.3 4.3 4.3]
 [4.3 4.3 4.3 4.3 4.3 4.3 4.3]
 [4.3 4.3 4.3 4.3 4.3 4.3 4.3]]

[[5.3 5.3 5.3 5.3 5.3 5.3 5.3]
 [5.3 5.3 5.3 5.3 5.3 5.3 5.3]
 [5.3 5.3 5.3 5.3 5.3 5.3 5.3]
 [5.3 5.3 5.3 5.3 5.3 5.3 5.3]]


In [30]:
x = np.array(
    [
        [1.2,2,3,4],
        [1,4,5,6],
        [1,2,3,4]
    ])
print (x)
y = np.array(
    [
        [1,2,3,4],
        [1,4,5,6],
        [1,2,3,4]
    ])
print (y)
print ()
z = np.add(x, y)
print (z)

[[1.2 2.  3.  4. ]
 [1.  4.  5.  6. ]
 [1.  2.  3.  4. ]]
[[1 2 3 4]
 [1 4 5 6]
 [1 2 3 4]]

[[ 2.2  4.   6.   8. ]
 [ 2.   8.  10.  12. ]
 [ 2.   4.   6.   8. ]]


##### 2) Matrix Subtraction  
<img src="image/matrix-sub.png">

In [24]:
z = x - y
print (z)
print ()
z = np.subtract(x, y)
print (z)

[[0.2 0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]

[[0.2 0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]


##### 3) Matrix Vector Multiplication
<img src="image/matrix-vector.png">

In [25]:
x = np.array(
    [
        [1,0,-1],
        [1,2,-1],
        [1,0,-1],
        [1,0,-1]
    ])
print (x)
y = np.array([1,1,2])
print (y)
z = np.dot(x, y)
print (z)

[[ 1  0 -1]
 [ 1  2 -1]
 [ 1  0 -1]
 [ 1  0 -1]]
[1 1 2]
[-1  1 -1 -1]


##### 3.1) Matrix Multiplication
<img src="image/matrix-dot.png">

In [26]:
x = np.array(
    [
        [1,2,3],
        [4,5,6]
    ])
print (x)
y = np.array(
    [
        [7,8],
        [9,10],
        [11,12]
    ])
print (y)
print ()
z = np.dot(x, y)
print (z)
print ()
z = np.dot(y, x)
print (z)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 58  64]
 [139 154]]

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


##### 4) Matrix Transpose
<img src="image/matrix-transpose.png">


In [27]:
x = np.array([[0,1,2,0], [0,3,4,5]])
print (x) 
print ()
print (x.T) 

[[0 1 2 0]
 [0 3 4 5]]

[[0 0]
 [1 3]
 [2 4]
 [0 5]]


<font color="red"> **Note that taking the transpose of a rank 1 array does nothing**

In [28]:
x = np.array([0,1,2,3])
print (x)
print (x.shape)
y = x.T
print (y.shape) 

[0 1 2 3]
(4,)
(4,)


<font color="red"> **Create an empty matrix with the same shape as x**    

In [29]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (x)
print ()
v = np.array([1, 5, 1])
y = np.empty_like(x)   

for i in range(4):
    y[i, :] = x[i, :] + v

print (y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 2  7  4]
 [ 5 10  7]
 [ 8 13 10]
 [11 16 13]]
