In [42]:
import torch
import torch.nn as nn

In [43]:
class LR(nn.Module):
  def __init__(self, input_size, output_size):
    super().__init__()
    self.linear = nn.Linear(input_size, output_size)
  def forward(self, x):
    pred = self.linear(x)
    return pred

In [44]:
torch.manual_seed(1)
model = LR(1,1)

In [60]:
x = torch.tensor([[1.0],[2.0]])
print(model.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)


In [61]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [62]:
[w, b] = model.parameters()

In [63]:
print(w[0,0].item())
print(b[0].item())

0.5152631998062134
-0.44137823581695557
