In [8]:
import numpy as np

In [22]:
A = np.array([[1, 0.3], [0.45, 1.2]])

In [23]:
A

array([[1.  , 0.3 ],
       [0.45, 1.2 ]])

In [24]:
U, s, V = np.linalg.svd(A)

In [25]:
s

array([1.49065822, 0.71444949])

In [26]:
U

array([[-0.58189652, -0.81326284],
       [-0.81326284,  0.58189652]])

In [27]:
V

array([[-0.63586997, -0.77179621],
       [-0.77179621,  0.63586997]])

In [28]:
w, v = np.linalg.eig(np.array([[1, -1], [1, 1]]))

In [29]:
w

array([1.+1.j, 1.-1.j])

In [30]:
v

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])