## Using NumPy

In this notebood we will cover numpy array: 

<li> Creating NumPy Arrays
<li> Create NumPy Array using built-in Methods
<li> <b>Array initialization</b>
<li> identity matrix
<li> linspace
<li> Lnitialization using random values
<li> <b>Array Attributes and Methods</b>
<li> shape, reshape, dtype
<li> max, min, argmax, argmin

In [2]:
import numpy as np

## NumPy Arrays

In [55]:
my_list = [1,2,3,4]
print( "my_list:", my_list)

my_list: [1, 2, 3, 4]


## Creating NumPy Arrays

In [59]:
np_array = np.array(my_list)
print(type(np_array))

<class 'numpy.ndarray'>


In [62]:
my_matrix = [[1,2,3],
             [4,5,6],
             [7,8,9]]

print("my_matrix:", my_matrix)
np.array(my_matrix)

my_matrix: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

Return evenly spaced values within a given interval. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]
<li> numpy.arange([start, ]stop, [step, ]dtype=None)

In [72]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

### zeros and ones

Generate arrays of zeros or ones. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace 
<li> numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0). Returns numbers evenly spaced samples, calculated over the interval [start, stop].

In [23]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [14]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### eye

Creates an identity matrix [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [73]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### random.rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over ``[0, 1)``. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [32]:
np.random.seed(7)
np.random.rand(2)

array([0.07630829, 0.77991879])

In [33]:
np.random.rand(2)

array([0.43840923, 0.72346518])

In [17]:
np.random.rand(5,5)

array([[0.03932992, 0.80719137, 0.50145497, 0.68816102, 0.1216304 ],
       [0.44966851, 0.92572848, 0.70802042, 0.10461719, 0.53768331],
       [0.12201904, 0.5940684 , 0.89979774, 0.3424078 , 0.77421593],
       [0.53191409, 0.0112285 , 0.3989947 , 0.8946967 , 0.2497392 ],
       [0.5814085 , 0.37563686, 0.15266028, 0.42948309, 0.26434141]])

### randn

Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike **rand** which is uniform, values closer to zero are more likely to appear. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

In [74]:
np.random.randn(2)

array([ 0.56927178, -0.20413855])

In [78]:
np.random.seed(7)
np.random.randn(5,5)

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02,
         4.07516283e-01, -7.88923029e-01],
       [ 2.06557291e-03, -8.90385858e-04, -1.75472431e+00,
         1.01765801e+00,  6.00498516e-01],
       [-6.25428974e-01, -1.71548261e-01,  5.05299374e-01,
        -2.61356415e-01, -2.42749079e-01],
       [-1.45324141e+00,  5.54580312e-01,  1.23880905e-01,
         2.74459924e-01, -1.52652453e+00],
       [ 1.65069969e+00,  1.54335535e-01, -3.87139943e-01,
         2.02907222e+00, -4.53860299e-02]])

### randint
Returns random integers from `low` (inclusive) to `high` (exclusive).  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

numpy.random.randint(low, high=None, size=None, dtype='l')

In [20]:
np.random.randint(1,100)

61

In [21]:
np.random.randint(1,100,10)

array([39, 50, 72, 18, 27, 59, 15, 97, 11, 14])

### seed
Can be used to set the random state, so that the same "random" results can be reproduced. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [22]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

Let's discuss some useful attributes and methods for an array:

In [37]:
np_array = np.arange(25)
np_random_array = np.random.randint(0,50,10)

In [38]:
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
np_random_array

array([38,  4, 48,  7, 44,  0, 11,  6, 19, 44])

## Reshape
Returns an array containing the same data with a new shape. [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [40]:
np_array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [41]:
np_random_array

array([38,  4, 48,  7, 44,  0, 11,  6, 19, 44])

In [42]:
np_random_array.max()

48

In [43]:
np_random_array.argmax()

2

In [44]:
np_random_array.min()

0

In [45]:
np_random_array.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):  [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [47]:
# Vector
np_array.shape

(25,)

In [48]:
# Notice the two sets of brackets
np_array.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [49]:
np_array.reshape(1,25).shape

(1, 25)

In [50]:
np_array.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [51]:
np_array.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array: [[reference](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [52]:
np_array.dtype

dtype('int64')

In [54]:
np_array = np.array([1.2, 3.4, 5.6])
np_array.dtype

dtype('float64')