# NumPy Indexing and Selection
<li>In this lecture we will discuss how to select elements or groups of elements from an array.

In [30]:
import numpy as np

In [31]:
np_array = np.arange(0,11)

In [32]:
print("np_array:", np_array)

np_array: [ 0  1  2  3  4  5  6  7  8  9 10]


## Bracket Indexing and Selection
<li>Get a value at an index
<li>Get values in a range
<li>Broadcasting - With NumPy arrays, you can broadcast a single value across a larger set of values. note the changes also occur in our original array!
<li>to get a copy use copy()

In [28]:
print(np_array[8])

8


In [33]:
print(np_array[1:5])

[1 2 3 4]


In [34]:
print("np_array:", np_array)

np_array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [35]:
np_array[0:5]=100
print("np_array:", np_array)

np_array: [100 100 100 100 100   5   6   7   8   9  10]


In [36]:
np_array = np.arange(0,11)
print("np_array:", np_array)

np_array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [37]:
slice_array = np_array[0:6]
print("slice_array:", slice_array)

slice_array: [0 1 2 3 4 5]


In [38]:
slice_array[:]=50
print("slice_array:", slice_array)
print("np_array:", np_array)

slice_array: [50 50 50 50 50 50]
np_array: [50 50 50 50 50 50  6  7  8  9 10]


In [39]:
np_array_copy = np_array.copy()
print("np_array_copy:", np_array_copy)

np_array_copy: [50 50 50 50 50 50  6  7  8  9 10]


## Indexing a 2D array (matrices)

The general format is **np_array_2d[row][col]** or **np_array_2d[row,col]**. 

<img src= 'numpy_indexing.png' width=500/> 

Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

In [40]:
np_array_2d = np.array(([5,10,15],
                        [20,25,30],
                        [35,40,45]))


np_array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [41]:
np_array_2d[1]

array([20, 25, 30])

In [42]:
np_array_2d[1][0]

20

In [43]:
np_array_2d[1,0]

20

In [44]:
np_array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
np_array_2d[2]

array([35, 40, 45])

In [46]:
np_array_2d[2,:]

array([35, 40, 45])

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part.

In [48]:
np_array = np.arange(1,11)
print("np_array:",np_array)

np_array: [ 1  2  3  4  5  6  7  8  9 10]


In [49]:
np_array > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
bool_array = np_array>4

In [56]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [57]:
np_array[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
np_array[np_array>6]

array([ 7,  8,  9, 10])

In [60]:
x = 2
np_array[np_array>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])